### ISSUE TITLE
Not always in English

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/questions-storage#2]
https://github.com/KA226-COVID/questions-storage/blob/6bac1151ffb749a92c52b9e8d4b238279b299fdf/src/main/java/com/juezlti/repository/controller/ExerciseController.java#L149

Lang must be chosen by user or by browser because we could have exercises without English statement.

**Comment by frasese** [comment]
Solved in [7184d3f4ce726bb59fb63468c9166e29f2d6d3b6](https://github.com/KA226-COVID/questions-storage/commit/7184d3f4ce726bb59fb63468c9166e29f2d6d3b6)
